"""
Conversation states for Telegram bot
Defines all possible states in the bot's conversation flow
"""

# Main conversation states
(MENU, GENERATE_TOPIC, GENERATE_TONE, GENERATE_PROVIDER, GENERATE_STYLE, 
 APPROVE_PLATFORMS, CREATE_CAPTION, CREATE_IMAGE, CREATE_PLATFORMS, 
 SCHEDULE_TIME, VIEW_SCHEDULE_DETAIL, LOGIN_ID, LOGIN_PASSWORD, 
 EDIT_CAPTION, EDIT_PLATFORM_SELECT) = range(15)

# State names for debugging
STATE_NAMES = {
    MENU: "MENU",
    GENERATE_TOPIC: "GENERATE_TOPIC",
    GENERATE_TONE: "GENERATE_TONE",
    GENERATE_PROVIDER: "GENERATE_PROVIDER",
    GENERATE_STYLE: "GENERATE_STYLE",
    APPROVE_PLATFORMS: "APPROVE_PLATFORMS",
    CREATE_CAPTION: "CREATE_CAPTION",
    CREATE_IMAGE: "CREATE_IMAGE",
    CREATE_PLATFORMS: "CREATE_PLATFORMS",
    SCHEDULE_TIME: "SCHEDULE_TIME",
    VIEW_SCHEDULE_DETAIL: "VIEW_SCHEDULE_DETAIL",
    LOGIN_ID: "LOGIN_ID",
    LOGIN_PASSWORD: "LOGIN_PASSWORD",
    EDIT_CAPTION: "EDIT_CAPTION",
    EDIT_PLATFORM_SELECT: "EDIT_PLATFORM_SELECT"
}

def get_state_name(state: int) -> str:
    """Get human-readable name for a state"""
    return STATE_NAMES.get(state, f"UNKNOWN_{state}")
